### ISSUE TITLE
Implement SVGO

### ISSUE THREAD

**Issue by TheJaredWilcurt** [Vekseid/FontReaper#1]
Automated, lossless, SVG optimization.
- https://github.com/svg/svgo

This should reduce your outputted CSS file dramatically.

You should also probably mention the gzip sizes as well.

For example `out-content.css` is **483KB**, but with maximum gzip compression it's **110KB**, and even with minimal gzip compression it's **123KB**. That's 75-78% reduction because there's so much repetition in an SVG spritesheet file. That reduction will likely go down once those SVG's are better optimized, but the end filesizes will go down as well, which is the more important part.

**Comment by Vekseid** [comment]
SVGO would not help with the current out-content.css - Font Awesome's glyphs are already fully optimized. Try optimizing the path statements or removing parts of the embedded uri - it often comes back larger in the former case, or will fail to work in the second.

**Comment by TheJaredWilcurt** [comment]
But is this a project to convert just FA, or is it a general purpose webfont-to-svg spritesheet converter.

If it's the later then you should definitely be using SVGO. If you want to go the extra mile and have it run it with and without SVGO and then keep the smaller of the two, that would be even better.

**Comment by Vekseid** [comment]
It's a fair thing to add, it's just not trivial, and will not help in the case of FA as its svg data comes pre-optimized.

**Comment by tomByrer** [comment]
I haven't use this yet, but I imagine I will soon, since I find many icons locked up in a font & would prefer not running Illustrator/Inkscape just to make some fonts into SVG.

Maybe a middle ground between full SVGO integration & nothing can be done easier?  I'm OK with having some sort of run an outside library manually between translating a font to SVG and collating SVG into CSS.  Maybe even splitting those two parts into separate files/programs?

**Comment by Vekseid** [comment]
Going over SVGO in detail, the only thing SVGO does that would affect this is comparing relative and absolute path declarations, and picking the shorter one.

Font Reaper currently only takes the path declaration, and assumes that it's not 'arbitrary svg data' as permitted by the W3C spec. So among other things it will assume that there are no transforms that need to be applied or consolidated, and it's going to straight up ignore everything that SVGO removes or consolidates, replacing it with the bare minimum that loads in IE9.

svgpath provides rel() and abs() methods, so that can be implemented without using SVGO. I'll do that quick and close this.
